enableScripts: false
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-prebuilds.js
    spec: .yarn/plugins/@yarnpkg/plugin-prebuilds.js
  - path: .yarn/plugins/@yarnpkg/plugin-redirect-app-builder.js
    spec: 'https://raw.githubusercontent.com/electricui/yarn-redirect-app-builder/master/bundles/%40yarnpkg/plugin-redirect-app-builder.js'
npmScopes:
  electricui:
    npmRegistryServer: 'https://registry.eui.io/'
prebuildHostMirrorTemplate: '{mirror_url}/{scopeWithAtAndSlash}{name}-v{version}-{runtime}-v{abi}-{platform}{libc}-{arch}.tar.gz'
prebuildHostMirrorUrl: 'https://registry.eui.io/prebuilds'
packageExtensions:
  chokidar@*:
    dependencies:
      fsevents: 2.1.3
  debug@*:
    dependencies:
      supports-color: 7.1.0
  react-layout-effect@*:
    dependencies:
      react: '*'
  use-memo-one@*:
    dependencies:
      react: '*'
  '@react-spring/web@*':
    dependencies:
      react-dom: '*'
  '@react-spring@*':
    dependencies:
      react-dom: '*'
  'react-dom@*':
    dependencies:
      react: '*'
  'react-three-fiber@*':
    dependencies:
      object-assign: '*'
  '@pmmmwh/react-refresh-webpack-plugin@*':
    dependencies:
      webpack: '*'
  'follow-redirects@*':
    dependencies:
      debug: '*'
  '@react-spring/core@*':
    dependencies:
      react: '*'
  '@react-spring/animated@*':
    dependencies:
      react: '*'
  '@react-spring/shared@*':
    dependencies:
      react: '*'
