plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-prebuilds.js
    spec: .yarn/plugins/@yarnpkg/plugin-prebuilds.js
enableScripts: false
packageExtensions:
  chokidar@*:
    dependencies:
      fsevents: 2.1.2
npmScopes:
  electricui:
    npmRegistryServer: '{{.Registry}}'
prebuildHostMirrorTemplate: '{mirror_url}/{scopeWithAtAndSlash}{name}-v{version}-{runtime}-v{abi}-{platform}{libc}-{arch}.tar.gz'
prebuildHostMirrorUrl: 'https://registry.eui.io/prebuilds'
